// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agqqxxfrnpuriwrmwdrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncXF4eGZybnB1cml3cm13ZHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMDAzNjAsImV4cCI6MjA3NjY3NjM2MH0.uox5JvNblqcQlSD6o-Rv4ZWYiVopVbyE-tnHSVjuVw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});